config/routes.rb
Jeffbook::Application.routes.draw do
  resources :users 
  resource :sessions, :only => [:new, :create, :destroy]
  root to: 'homepage#show'

end

app/models/user.rb
p "loading user model..."

class User < ActiveRecord::Base
   attr_accessible :name, :password, :about
   validates :name, uniqueness: true, presence: true
   validates :password, presence: true, length: {minimum: 4}
   validates :about, length: {maximum: 250 }
   
   
   def create_session_token
     new_token = SecureRandom.urlsafe_base64
     self.session_token = new_token
     self.save
     new_token
   end
     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
 
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end
  
  def create
    @user = User.find_by_name_and_password(params[:session][:name], 
                                           params[:session][:password])
    if @user
      flash[:success] ="Welcome back, #{@user.name}"
      login(@user)
      redirect_to @user
      
    else
      flash[:fail] = "Blew it on the name/password thing"
      render :new
    end
  end
  
  def destroy
    flash[:success] = "Signed out."
    log_out
    redirect_to root_url
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:show, :index, :destroy]
  before_filter :correct_user, only: [:show, :index, :destroy]
  def new
    @user = User.new
    render :new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Account created."
      login(@user)
      redirect_to @user
    else
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
    render :show
  end
  
  def index
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.delete
    redirect_to root_url
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def login(user)
    session[:session_token] = user.create_session_token
    flash[:token] = "#{session[:session_token]}  is the session token"
    self.current_user = user
  end
  
  def log_out
    session[:session_token] = nil
    # current_user.session_token = nil
    current_user = nil
  end
  
  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user?(user)
    current_user == user
  end
  
  def logged_in?
    !!current_user
  end
  
  def signed_in_user
    if !logged_in?
      flash[:notice] = "Please sign in."
      redirect_to new_sessions_url
    end
  end
  
  def correct_user
    @user = User.find(params[:id])
    unless current_user?(@user)
      flash[:notices] = "You are not allowed to do that."
      redirect_to new_sessions_url unless logged_in?
      redirect_to current_user if logged_in?
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homepage/show.html.erb
<br>
<h1> Welcome To JeffBook </h1>
<%= image_tag("headshot.jpg") %>
<h2> The world's worst social network!</h2>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jeffbook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% flash.each do |key, val| %>
		<%= "#{key.to_s.upcase}! #{val}" %>
	<% end %>
	<br>
	<%= render 'shared/header' %>
	<br>
	<%= yield %>
	<br>
	<%= render 'shared/footer' %>
</body>
</html>

app/views/shared/_footer.html.erb
<% unless logged_in?%>
	<%= link_to 'Create Account' , new_user_url%>
<% end %>
<%= link_to 'Home', root_url%>

app/views/shared/_header.html.erb
<% if logged_in? %>
<%=link_to 'Profile', current_user%>
<%=link_to 'Friends', '#'%>
<%=link_to 'Log Out', sessions_url, method: 'delete'%>
<% else %>
<%=link_to 'Login', new_sessions_url%>
<% end%>

app/views/users/new.html.erb
<br>
<% if @user.errors.any? %>
	<% @user.errors.full_messages.each do |error| %>
		<%= error %>
		<br>
	<% end %>
<% end %>
<h1> Sign up for an account at JeffBook </h1>

<%= form_for(@user) do |f| %>

<%= f.text_field :name %>
<%= f.label :name, "Enter you Name"%>
<br>
<%= f.password_field :password %>
<%= f.label :password, "Enter a Password"%>
<br>
<%= f.text_area :about %>
<br>
<%= f.label :about, "Tell us a little about yourself (max 250 characters)"%>
<br>
<%= f.submit "SUBMIT YOUR FIRST BORN"%>
<% end %>
	
	
	

app/views/users/show.html.erb
<br>
<h1> Hello <%=@user.name%>, this is your page </h1>
<br>
<%=@user.about%>
<br>
<br>
<%= link_to "Edit my info", '#'%>
<%= link_to "Delete my account", user_url, method: "delete"%>
<br>